sudo: false
language: python
python: '2.7'
# cache: pip
cache:
  directories:
    - $HOME/.pip-cache/
os: linux
install:
- pip install --upgrade pip --cache-dir $HOME/.pip-cache
- pip install mkdocs --cache-dir $HOME/.pip-cache
script:
- mkdocs build --verbose --clean --strict
notifications:
  email: true
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: docs
 keep-history: true
 on:
   branch: master
 fqdn: www.docs.iprofor.it # enables Travis CI to automatically create the CNAME file under xxx.github.io repository.
